name: time
description: A DateTime extension to easily manipulate DateTime.now()
version: 0.0.1
author: Maximilian Auer

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.9.0
