name: time
description: A DateTime extension to easily manipulate DateTime.now()
version: 1.0.0
author: Maximilian Auer

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.7
